FROM maven:3.9.4 AS build

COPY ../target /app/target

FROM eclipse-temurin:17

COPY --from=build /app/target/cloud-file-storage-0.0.1-SNAPSHOT.jar /usr/local/lib/cloud-file-storage.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/usr/local/lib/cloud-file-storage.jar"]