version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../data/postgres-data:/var/lib/postgresql/data
      - ../data/init-scripts:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    container_name: minio-container
    environment:
      MINIO_ACCESS_KEY: youraccesskey
      MINIO_SECRET_KEY: yoursecretkey
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../data/minio-data:/data
    command: server --console-address ":9001" /data
  cloud-file-storage:
    container_name: cloud-file-storage
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: cloud-file-storage
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_HOST: http://minio:9000
      MINIO_ACCESS_KEY: youraccesskey
      MINIO_SECRET_KEY: yoursecretkey
      MINIO_FILES_BUCKET: user-files
