version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../data/postgres-data:/var/lib/postgresql/data
      - ../data/init-scripts:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio:latest
    container_name: minio-container
    environment:
      MINIO_ACCESS_KEY: youraccesskey
      MINIO_SECRET_KEY: yoursecretkey
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../data/minio-data:/data
    command: server --console-address ":9001" /data
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
