name: Docker Image build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Start Docker
        run: |
          sudo service docker start
          sudo chmod 666 /var/run/docker.sock

      - name: Run Testcontainers Tests
        run: mvn test

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/cloud-file-storage:0.1-BUILD${{ github.run_number }} --platform linux/amd64,linux/arm64 .
          docker buildx use default
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cloud-file-storage:0.1-BUILD${{ github.run_number }}
