name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Checkstyle validation
      run: mvn validate
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: Cloud file storage jar build
        path: target/cloud-file-storage-0.0.1-SNAPSHOT.jar
