name: Java CI with Maven and Testcontainers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dcheckstyle.skip=true

      - name: Start Docker
        run: |
          sudo service docker start
          sudo chmod 666 /var/run/docker.sock

      - name: Run Testcontainers Tests
        run: mvn test

      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: Cloud file storage jar build
          path: target/cloud-file-storage-0.0.1-SNAPSHOT.jar
